spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pws
    username: pws
    password: pws
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info